// ========== 语言配置数据 ==========
const LANGUAGES = [
  {
    id: 'html',
    name: 'HTML',
    enName: 'HyperText Markup',
    icon: '🧱',
    description: '网页结构基础，构建一切的起点',
    color1: '#e34f26',
    color2: '#f06529',
    glow: 'rgba(227, 79, 38, 0.4)',
    levels: 12,
    difficulty: '入门',
    gameplay: '建造师',
  },
  {
    id: 'css',
    name: 'CSS',
    enName: 'Cascading Style',
    icon: '🎨',
    description: '美化你的网页，让设计栩栩如生',
    color1: '#2965f1',
    color2: '#264de4',
    glow: 'rgba(41, 101, 241, 0.4)',
    levels: 15,
    difficulty: '入门',
    gameplay: '变形记',
  },
  {
    id: 'javascript',
    name: 'JavaScript',
    enName: 'Dynamic Scripting',
    icon: '✨',
    description: '赋予网页灵魂，实现交互与逻辑',
    color1: '#f7df1e',
    color2: '#f0db4f',
    glow: 'rgba(247, 223, 30, 0.4)',
    levels: 20,
    difficulty: '进阶',
    gameplay: '魔法学院',
  },
  {
    id: 'vue',
    name: 'Vue',
    enName: 'Progressive Framework',
    icon: '♟️',
    description: '渐进式框架，轻松构建现代应用',
    color1: '#42b883',
    color2: '#35495e',
    glow: 'rgba(66, 184, 131, 0.4)',
    levels: 18,
    difficulty: '进阶',
    gameplay: '策略棋盘',
  },
  {
    id: 'python',
    name: 'Python',
    enName: 'Readable & Clean',
    icon: '🥷',
    description: '简洁优雅，人工智能首选语言',
    color1: '#3776ab',
    color2: '#2563eb',
    glow: 'rgba(55, 118, 171, 0.4)',
    levels: 22,
    difficulty: '入门',
    gameplay: '忍者训练',
  },
  {
    id: 'java',
    name: 'Java',
    enName: 'Write Once Run Anywhere',
    icon: '🤖',
    description: '企业级开发标杆，跨平台王者',
    color1: '#ea2d2e',
    color2: '#c0392b',
    glow: 'rgba(234, 45, 46, 0.4)',
    levels: 25,
    difficulty: '高级',
    gameplay: '模拟机器人',
  },
  {
    id: 'cpp',
    name: 'C/C++',
    enName: 'High Performance',
    icon: '🏎️',
    description: '高性能系统编程，游戏引擎之基',
    color1: '#00599c',
    color2: '#004482',
    glow: 'rgba(0, 89, 156, 0.4)',
    levels: 28,
    difficulty: '高级',
    gameplay: '底层赛车',
  },
  {
    id: 'csharp',
    name: 'C#',
    enName: 'Modern Microsoft',
    icon: '🎯',
    description: '.NET 生态核心，Unity 游戏开发首选',
    color1: '#9b4f96',
    color2: '#68217a',
    glow: 'rgba(155, 79, 150, 0.4)',
    levels: 24,
    difficulty: '高级',
    gameplay: '射击游戏',
  },
  {
    id: 'uniapp',
    name: 'Uni-app',
    enName: 'Cross-Platform',
    icon: '📱',
    description: '一次开发多端发布，小程序神器',
    color1: '#00dc82',
    color2: '#363593',
    glow: 'rgba(0, 220, 130, 0.4)',
    levels: 16,
    difficulty: '进阶',
    gameplay: '生活模拟',
  },
];

// 导出为全局变量
window.LANGUAGES = LANGUAGES;
